# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      REPOSITORY_URL: https://github.com/${{ github.repository }}.git
      PROJECT_URL: https://github.com/${{ github.repository }}
      BUILD_NUMBER: ${{ github.run_number }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your ${{ github.ref_type }} is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore --nologo

      - name: dotnet pack
        run: dotnet pack -c Release -o dist --no-restore --no-build --nologo

      - name: upload artifacts (github)
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist

      - name: dotnet nuget push (github)
        run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate
        if: |
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || github.ref_type == 'tag')

      - name: dotnet nuget push (nuget)
        run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate --source "nuget.org" --api-key ${{secrets.NUGET_API_KEY}}
        if: github.event_name == 'push' && github.ref_type == 'tag'

      - name: create release (github)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*.nupkg"
        if: github.event_name == 'push' && github.ref_type == 'tag'
